using System;

namespace BloodTracker.Infrastructure.Services;

internal static class BloodTestNameMapper
{
    public static readonly Dictionary<string, string[]> NameMappings = new(StringComparer.OrdinalIgnoreCase)
    {
        ["free-testosterone"] = ["Тестостерон свободный", "свободный (расч", "свободный"],
        ["testosterone"] = ["Тестостерон общий"],
        ["lh"] = ["Лютеинизирующий гормон", "гормон (ЛГ)", "(ЛГ)"],
        ["fsh"] = ["Фолликулостимулирующий гормон", "гормон (ФСГ)", "(ФСГ)"],
        ["prolactin"] = ["Пролактин"],
        ["estradiol"] = ["Эстрадиол, ВЭЖХ", "Эстрадиол"],
        ["estriol"] = ["Эстриол, ВЭЖХ", "Эстриол"],
        ["estrone"] = ["Эстрон, ВЭЖХ", "Эстрон"],
        ["shbg"] = ["ГСПГ", "Глобулин, связывающий половые", "связывающий половые", "SHBG"],
        ["tsh"] = ["Тиреотропный гормон", "гормон (ТТГ)", "(ТТГ)", "(TTT)", "ТТГ)"],
        ["igf1"] = ["ИФР-1", "IGF-1", "Соматомедин"],
        ["fai"] = ["Индекс свободных андрогенов", "свободных андрогенов"],

        ["hdl"] = ["липопротеидов высокой плотности", "ЛПВП, HDL", "(ЛПВП", "ЛПВП,", "HDL"],
        ["ldl"] = ["липопротеидов низкой плотности", "ЛПНП, LDL", "(ЛПНП", "ЛПНП,", "LDL", "JITTHIT"],
        ["vldl"] = ["ЛПОНП", "VLDL", "очень низкой плотности"],
        ["non-hdl-cholesterol"] = ["Холестерин не-ЛПВП", "не-ЛПВП", "не ЛПВП"],
        ["triglycerides"] = ["Триглицериды"],
        ["cholesterol"] = ["Холестерин общий", "Холестерол общий", "Холестерин общ"],
        ["atherogenic"] = ["Коэффициент атерогенности", "атерогенности"],
        ["apolipoprotein-a1"] = ["Аполипопротеин А1", "Аполипопротеин A1", "Apolipoprotein A1"],
        ["apolipoprotein-b"] = ["Аполипопротеин В", "Аполипопротеин B", "Apolipoprotein B"],
        ["lipoprotein-a"] = ["Липопротеин (а)", "Липопротеин(а)", "Lipoprotein(a)"],

        ["alt"] = ["Аланинаминотрансфераза", "(АЛТ)", "АЛТ)", "АЛТ"],
        ["ast"] = ["Аспартатаминотрансфераза", "(АСТ)", "АСТ)", "АСТ", "Аспартат"],
        ["ggt"] = ["Гамма-глутамилтрансфераза", "(ГГТ)", "ГГТ)", "ГГТ"],
        ["alp"] = ["Щелочная фосфатаза", "Щелочная", "фосфатаза"],
        ["cholinesterase"] = ["Холинэстераза", "Cholinesterase"],

        ["bilirubin-direct"] = ["Билирубин прямой", "Билирубин, прямой"],
        ["bilirubin"] = ["Билирубин общий", "Билирубин, общий", "Билирубин o6щий", "Билирубин общ"],

        ["glucose"] = ["Глюкоза"],
        ["hba1c"] = ["Гликированный гемоглобин", "HbA1c"],
        ["creatinine"] = ["Креатинин"],
        ["urea"] = ["Мочевина"],
        ["protein"] = ["Общий белок", "белок общий", "Белок общий"],
        ["vitd"] = ["Витамин D", "25-OH", "25-ОН"],

        ["pt"] = ["Протромбиновое время"],
        ["pt-percent"] = ["Протромбин %", "по Квику", "Протромбин % (по"],
        ["inr"] = ["МНО", "нормализованное отношение", "INR", "(МНО)", "отношение (МНО)"],

        ["hemoglobin"] = ["Гемоглобин"],
        ["hematocrit"] = ["Гематокрит"],
        ["erythrocytes"] = ["Эритроциты"],
        ["mcv"] = ["Средний объем эритроцитов", "(MCV)", "MCV"],
        ["mchc"] = ["Средняя концентрация Hb в эритроцитах", "(МСНС)", "МСНС", "MCHC"],
        ["mch"] = ["Среднее содержание гемоглобина в эритроците", "(МСН)", "МСН)", "MCH"],
        ["rdw-sd"] = ["ширина распред.эритр.по объему (ст.отклонение)", "распред.эритр.по объему (ст.откл", "RDW-SD"],
        ["rdw-cv"] = ["ширина распред.эритр.по объему(коэфф.вариации)", "распред.эритр.по объему(коэфф", "RDW-CV", "ширина распред.эритр.по объему (коэфф"],
        ["platelets"] = ["Тромбоциты"],
        ["mpv"] = ["Средний объем тромбоцитов", "(MPV)", "MPV"],
        ["pct-platelet"] = ["Тромбокрит", "(PCT)", "PCT"],
        ["pdw"] = ["ширина распред.тромбоцитов по объему", "(PDW)", "PDW"],
        ["wbc"] = ["Лейкоциты"],
        ["neutrophils"] = ["Нейтрофилы"],
        ["neutrophils-percent"] = ["Нейтрофилы %"],
        ["eosinophils"] = ["Эозинофилы"],
        ["eosinophils-percent"] = ["Эозинофилы %"],
        ["basophils"] = ["Базофилы"],
        ["basophils-percent"] = ["Базофилы %"],
        ["monocytes"] = ["Моноциты"],
        ["monocytes-percent"] = ["Моноциты %"],
        ["lymphocytes"] = ["Лимфоциты"],
        ["lymphocytes-percent"] = ["Лимфоциты %"],

        ["afp"] = ["Альфа-фетопротеин", "(АФП)", "АФП"],

        ["albumin"] = ["Альбумин"],
        ["albumin-percent"] = ["Альбумин %"],
        ["alpha1-globulin"] = ["Альфа-1 глобулин"],
        ["alpha1-globulin-percent"] = ["Альфа-1 глобулин, %", "Альфа-1 глобулин,%"],
        ["alpha2-globulin"] = ["Альфа-2 глобулин"],
        ["alpha2-globulin-percent"] = ["Альфа-2 глобулин, %", "Альфа-2 глобулин,%"],
        ["beta1-globulin"] = ["Бета-1 глобулин"],
        ["beta1-globulin-percent"] = ["Бета-1 глобулин, %", "Бета-1 глобулин,%"],
        ["beta2-globulin"] = ["Бета-2 глобулин"],
        ["beta2-globulin-percent"] = ["Бета-2 глобулин, %", "Бета-2 глобулин,%"],
        ["gamma-globulin"] = ["Гамма-глобулин"],
        ["gamma-globulin-percent"] = ["Гамма-глобулин, %", "Гамма-глобулин,%"]
    };

    public static readonly Dictionary<string, (double Min, double Max)> ExpectedRanges = new()
    {
        ["testosterone"] = (0.5, 120),
        ["free-testosterone"] = (0.01, 10),
        ["lh"] = (0, 50),
        ["fsh"] = (0, 50),
        ["prolactin"] = (20, 2500),
        ["estradiol"] = (5, 500),
        ["estriol"] = (0, 100),
        ["estrone"] = (10, 500),
        ["shbg"] = (1, 200),
        ["tsh"] = (0.01, 20),
        ["igf1"] = (30, 600),
        ["fai"] = (1, 3000),
        ["cholesterol"] = (2, 12),
        ["hdl"] = (0.3, 4),
        ["ldl"] = (0.3, 8),
        ["triglycerides"] = (0.1, 10),
        ["vldl"] = (0.05, 3),
        ["atherogenic"] = (0.3, 15),
        ["non-hdl-cholesterol"] = (0.5, 10),
        ["apolipoprotein-a1"] = (0.3, 3),
        ["apolipoprotein-b"] = (0.2, 3),
        ["lipoprotein-a"] = (0, 200),
        ["alt"] = (1, 500),
        ["ast"] = (1, 500),
        ["ggt"] = (1, 300),
        ["alp"] = (10, 500),
        ["cholinesterase"] = (2, 20),
        ["bilirubin"] = (1, 100),
        ["bilirubin-direct"] = (0, 30),
        ["glucose"] = (1, 30),
        ["hba1c"] = (3, 15),
        ["creatinine"] = (20, 400),
        ["urea"] = (0.5, 30),
        ["protein"] = (30, 120),
        ["vitd"] = (3, 200),
        ["pt"] = (5, 30),
        ["pt-percent"] = (30, 200),
        ["inr"] = (0.3, 5),
        ["hemoglobin"] = (50, 250),
        ["hematocrit"] = (15, 70),
        ["erythrocytes"] = (2, 8),
        ["mcv"] = (50, 120),
        ["mchc"] = (25, 40),
        ["mch"] = (15, 40),
        ["rdw-sd"] = (25, 70),
        ["rdw-cv"] = (8, 25),
        ["platelets"] = (50, 600),
        ["mpv"] = (5, 20),
        ["pct-platelet"] = (0.05, 0.6),
        ["pdw"] = (5, 25),
        ["wbc"] = (1, 30),
        ["neutrophils"] = (0.5, 20),
        ["neutrophils-percent"] = (10, 90),
        ["eosinophils"] = (0, 2),
        ["eosinophils-percent"] = (0, 15),
        ["basophils"] = (0, 0.5),
        ["basophils-percent"] = (0, 3),
        ["monocytes"] = (0.05, 3),
        ["monocytes-percent"] = (1, 20),
        ["lymphocytes"] = (0.3, 10),
        ["lymphocytes-percent"] = (5, 70),
        ["afp"] = (0, 50),
        ["albumin"] = (20, 60),
        ["albumin-percent"] = (40, 80),
        ["alpha1-globulin"] = (1, 6),
        ["alpha1-globulin-percent"] = (1, 8),
        ["alpha2-globulin"] = (2, 15),
        ["alpha2-globulin-percent"] = (3, 18),
        ["beta1-globulin"] = (1, 8),
        ["beta1-globulin-percent"] = (2, 12),
        ["beta2-globulin"] = (1, 8),
        ["beta2-globulin-percent"] = (1, 10),
        ["gamma-globulin"] = (3, 25),
        ["gamma-globulin-percent"] = (5, 30)
    };

    public static bool ValidateValue(string key, double value)
    {
        if (!ExpectedRanges.TryGetValue(key, out var range))
            return true;

        return value >= range.Min && value <= range.Max;
    }
}
